  export const portfolioProjects = [
    {
      id: 1,
      title: "Pesantren Tuli: 'Bagaimana Mau Taat Kalau Gak Pernah Dengar?'",
      year: "2022",
      platform: "VOA Indonesia",
      description: "Di agama yang ibadahnya sarat dengan praktik lisan, bagaimana teman Tuli beribadah di agama Islam?",
      tags: ["Documentary", "religion"],
      language: "bahasa",
      videoUrl: "https://www.youtube.com/watch?v=YdxiQLmk8pI"
    },
    {
      id: 2,
      title: "Waria Tenang Beribadah di Pesantren Al-Fatah",
      year: "2021",
      platform: "VOA Indonesia",
      description: "",
      tags: ["documentary", "religion", "Transgender"],
      language: "bahasa",
      videoUrl: "https://www.youtube.com/watch?v=UZXx8HFxZIg"
    },
    {
      id: 3,
      title: "Guru SD Transpuan di Flores Timur: Jangan Panggil Saya 'Pak'",
      year: "2023",
      platform: "VOA Indonesia",
      description: "Sebenarnya ada penolakan dalam diri saya. Saya sudah berdandan untuk pergi bekerja, namun masih dipanggil ‘pak’",
      tags: ["docuemntary", "transgender"],
      language: "bahasa",
      videoUrl: "https://www.youtube.com/watch?v=BH5IysQYddE"
    },
    {
      id: 4,
      title: "Can Covid Patients Recover?",
      year: "2021",
      platform: "VOA Indonesia",
      description: "Treatments toward COVID-19 infection keeps developing along with the more knowledge to understand behavior of this virus is gained. WHO on May has actually announced a new procedure basically saying that patients will no longer required 2x consecutive negative swab test result in order to be considered recovered from the disease. ",
      image: "/img/2(1).png",
      tags: ["Covid-19"],
      language: "bahasa",
      videoUrl: 'https://www.linkedin.com/feed/update/urn:li:activity:6723813398838165504/'
    },
    {
      id: 5,
      title: "Indonesians Are Trying to Make Crypto Halal",
      year: "2022",
      platform: "VICE News",
      description: "Cryptocurrency is booming in Indonesia, with millions of Indonesians looking to crypto investments as a way of making quick money after two years of pandemic-fueled economic decline. But in the world’s most populous Muslim country, religious authorities have spoken out against the risks of cryptocurrency, and declared crypto transactions against the rules of Islam.",
      tags: ["covid-19", "Cryptocurrency"],
      language: "english",
      videoUrl: "https://www.youtube.com/watch?v=Z5oXzNUz7G0"
    },
    {
      id: 6,
      title: "Only 37% of Indonesian are willing to take COVID-19 vaccine",
      year: "2021",
      platform: "VOA Indonesia",
      description: "According to the latest survey by SMRC (16-19 Dec 2020). I asked around, why not? Here is what they say, responded by expert and Indonesian vaccine spokesperson.",
      tags: ["Vaccine", "Covid-19"],
      language: "bahasa",
      image: "/img/3.png",
      videoUrl: 'https://www.linkedin.com/feed/update/urn:li:activity:6751693570811535360/'
    },
    {
      id: 7,
      title: "Diaspora Indonesia Tinggal di Kawasan ‘Zombie’ Narkoba di Philadelphia",
      year: "2023",
      platform: "VOA Indonesia",
      description: "Behind the drug 'zombie' phenomenon in the Kensington Avenue area of Philadelphia, United States, it turns out there is an Indonesian diaspora family who has lived there for 15 years.",
      tags: ["narcotics"],
      language: "bahasa",
      videoUrl: "https://www.youtube.com/watch?v=7gut7W-AUjI",
    },
    {
      id: 8,
      title: "Indonesian Diver Volunteers, Treating Airplane Crash Victims as Human and With Respect",
      year: "2023",
      platform: "VOA Indonesia",
      description: "Volunteering in your community is not a new idea. But for one Indonesian scuba diver his volunteer work is dangerous and sometimes terrifying. ",
      tags: ["Diver"],
      language: "english",
      videoUrl: "https://www.youtube.com/watch?v=U8SZhhfABQo",
    },
    {
      id: 9,
      title: "Inside Indonesia's Only Quran School for Trans Muslims | Transnational",
      year: "2022",
      platform: "VICE News",
      description: "In this episode of Transnational, Rana Thamrin embarks on a spiritual journey to Indonesia’s only Islamic school in Yogyakarta where transgender Muslim women are finding ways to reconcile their faith and trans identity.",
      tags: ["Trandgender", "News"],
      language: "english",
      videoUrl: "https://www.youtube.com/watch?v=BN_yIxQABOA",
    },
    {
      id: 10,
      title: "Erosion and groundwater extraction cause Indonesian villages to disappear under water",
      year: "2022",
      platform: "South China Morning Post",
      description: "Villages in Demak on the northern coast of Indonesia's Central Java have slowly but surely been disappearing under water, as erosion and groundwater extraction have caused the land to sink below sea level. Seven villages have been submerged so far, with most residents having to relocate. But a few still choose to live in their homes that are flooded on a daily basis.",
      tags: ["documentary", "Erosion"],
      language: "english",
      videoUrl: "https://www.youtube.com/watch?v=a8f2hvCrcaI",
    },
    {
      id: 11,
      title: "Indonesian Trans Women Leave Streets to Operate Laundry",
      year: "2021",
      platform: "VOA Indonesia",
      description: "When an Indonesian American, a recent college graduate, collected a $10,000 peace prize she spent the money as soon as she could to realize her winning plan – providing aging trans women in Jakarta with a steady income from a laundry business, freeing them from sex work and begging.",
      tags: ["documentary", "Transgender"],
      language: "english",
      image: '/img/26.webp',
      videoUrl: "https://www.voanews.com/a/indonesian-trans-women-leave-streets-to-operate-laundry/6317123.html",
    },
    {
      id: 12,
      title: "NY Fashion Show Aims to Educate, Dispell Stigma of Sexual Assault",
      year: "2023",
      platform: "VOA Indonesia",
      description: "New York Fashion Week is generally known as a showcase for fashion designers, and the celebrities that wear their clothes. But several shows held on the sidelines are trying to call attention not only to fashion but to serious and difficult issues like sexual assault. VOA’s Rendy Wicaksana reports from New York",
      tags: ["documentary", "Sexual Assault"],
      language: "english",
      image: '/img/27.webp',
      videoUrl: "https://www.voanews.com/a/ny-fashion-show-aims-to-educate-dispell-stigma-of-sexual-assault/7273475.html",
    },
    {
      id: 13,
      title: "In Indonesia, Predatory Loan Apps Boom Amid Pandemic Hardships",
      year: "2021",
      platform: "VOA Indonesia",
      description: "Scammers have long preyed upon the economically vulnerable. But in Indonesia, economic hardship and increased online activity during the COVID pandemic have led to a boom in predatory loan apps",
      tags: ["documentary", "Loans"],
      language: "english",
      image: '/img/28.webp',
      videoUrl: "https://www.voanews.com/a/in-indonesia-predatory-loan-apps-boom-amid-pandemic-hardships/6272042.html",
    },
    {
      id: 14,
      title: "Wheelchair Badminton USAGM",
      year: "2021",
      platform: "VOA Indonesia",
      description: "Parasports — sports events involving athletes with disabilities — often don’t get as much attention as comparable events for nondisabled athletes. And this is also the case with badminton",
      tags: ["documentary", "Parasports", "Badminton"],
      language: "english",
      image: '/img/29.webp',
      videoUrl: "https://www.voanews.com/a/6266320.html",
    },
    {
      id: 15,
      title: "Indonesia’s Isolated Baduy Use Internet to Survive Pandemic",
      year: "2021",
      platform: "VOA Indonesia",
      description: "Many isolated tribes have been affected by the COVID-19 pandemic. One such tribe in Indonesia, the Baduy Tribe has been devastated economically. To survive, some members of the community have embraced a local taboo",
      tags: ["documentary", "Covid-19", "Baduy Tribe"],
      language: "english",
      image: '/img/30.webp',
      videoUrl: "https://www.voanews.com/a/episode_indonesias-isolated-baduy-use-internet-survive-pandemic-4765711/6117931.html",
    },
    {
      id: 16,
      title: "Pandemic Compounds Troubles for Afghan Refugees in Indonesia",
      year: "2020",
      platform: "VOA Indonesia",
      description: "The COVID-19 pandemic continues to make life even more difficult for thousands of refugees in Indonesia who have no access to formal work or school. Many are awaiting resettlement to another country, while relying on relatives in other countries who are also dealing with business shutdowns.",
      tags: ["documentary", "Refugees"],
      language: "english",
      image: '/img/31.webp',
      videoUrl: "https://www.voanews.com/a/episode_pandemic-compounds-troubles-afghan-refugees-indonesia-4327786/6110766.html",
    },
    {
      id: 17,
      title: "Global Vaccine Distribution Inequality Hampers Pandemic Efforts Worldwide",
      year: "2021",
      platform: "VOA Indonesia",
      description: "Global inequality in the distribution of vaccines continues to hamper efforts to end the pandemic worldwide. But for those able to travel to wealthier countries with an abundance of vaccines, they are now willing to travel the distance and bear the high cost of “vaccine tourism”.",
      tags: ["documentary", "Covid-19", "Vaccines"],
      language: "english",
      image: '/img/32.webp',
      videoUrl: "https://www.voanews.com/a/episode_global-vaccine-distribution-inequality-hampers-pandemic-efforts-worldwide-4749181/6117672.html",
    },
    {
      id: 18,
      title: "Indonesia Child Mortality Rate Spikes Amid COVID-19 Surge",
      year: "2021",
      platform: "VOA Indonesia",
      description: "Indonesia is struggling with another peak of COVID-19. Infections topped two million in June, with the Delta variant driving the current surge. And as the county’s pediatricians point out, 1 out of 8 of confirmed cases are found in children and the fatality rate among children is the highest in the world.",
      tags: ["documentary", "Covid-19", "Children"],
      language: "english",
      image: '/img/33.webp',
      videoUrl: "https://www.voanews.com/a/episode_indonesia-child-mortality-rate-spikes-amid-covid-19-surge-4731971/6117431.html",
    },
    {
      id: 19,
      title: "A Bali Village Works Together to Compost Organic Waste",
      year: "2021",
      platform: "VOA Indonesia",
      description: "A small village in Indonesia is sending less and less of their household waste to landfills. Instead, the village is composting the waste, which is then sold to local farmers for use as livestock feed.",
      tags: ["documentary", "Bali Village", "Compost"],
      language: "english",
      image: '/img/35.webp',
      videoUrl: "https://www.voanews.com/a/episode_bali-village-works-together-compost-organic-waste-4602451/6115445.html",
    },
    {
      id: 20,
      title: "Big City Teleworkers Migrate to Bali Resorts During Pandemic",
      year: "2020",
      platform: "VOA Indonesia",
      description: "Up until recently, the Indonesian tourist destination of Bali has seen empty beaches and hotel rooms. But that’s changing in a most unusual way.",
      tags: ["documentary", "Bali Resorts", "Pandemic"],
      language: "english",
      image: '/img/36.webp',
      videoUrl: "https://www.voanews.com/a/episode_big-city-teleworkers-migrate-bali-resorts-during-pandemic-4485591/6113431.html",
    },
    {
      id: 21,
      title: "Indonesia Links Up with Chinese Pharmaceutical on COVID Vaccine",
      year: "2020",
      platform: "VOA Indonesia",
      description: "More and more COVID vaccines are entering phase three of clinical trials. Several Chinese pharmaceuticals are among those developing vaccines, and Indonesia has decided to partner with them. But researchers in Indonesia are also looking to develop their own homegrown vaccine.",
      tags: ["documentary", "Covid-19", "Vaccines"],
      language: "english",
      image: '/img/37.webp',
      videoUrl: "https://www.voanews.com/a/episode_indonesia-links-chinese-pharmaceutical-covid-vaccine-4395276/6111897.html",
    },
    {
      id: 22,
      title: "Serving Equality With A Cup of Coffee",
      year: "2020",
      platform: "VOA Indonesia",
      description: "Coffee is one of the most popular hot beverages in the world and is drunk almost daily by about a third of the world’s population. At a coffee shop in Jakarta, Indonesia, the owners want to promote communication, understanding and tolerance by employing people who can’t hear.",
      tags: ["documentary", "Equality", "Coffee"],
      language: "english",
      image: '/img/38.webp',
      videoUrl: "https://www.voanews.com/a/serving-equality-with-a-cup-of-coffee/5266823.html",
    },
    {
      id: 23,
      title: "The Price of Beijing's Vaccine Diplomacy in Southeast Asia",
      year: "2020",
      platform: "VOA Indonesia",
      description: "As China publicly claims it is closing in on a coronavirus vaccine, Beijing has begun promising early access to countries of strategic interest. The effort is broadly seen as a way for Beijing to try to shore up its global standing after the outbreak that started in Wuhan spread to the rest of the world.",
      tags: ["documentary", "Vaccines", "Beijing"],
      language: "english",
      image: '/img/39.webp',
      videoUrl: "https://www.voanews.com/a/east-asia-pacific_voa-news-china_price-beijings-vaccine-diplomacy-southeast-asia/6195787.html",
    },
  ];